// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxzPtGQDArggGosRF-oxjxIZ49yX0DuE',
    appId: '1:565519577576:web:6d9721c5c985f0c558345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    authDomain: 'sayer-app-e9af3.firebaseapp.com',
    storageBucket: 'sayer-app-e9af3.appspot.com',
    measurementId: 'G-CRNL1PM2EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCduqWM74aoNrrsTlikpPaptVWHjvImEXs',
    appId: '1:565519577576:android:9dcf687878a60a5058345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    storageBucket: 'sayer-app-e9af3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvRIUWLluw6vAIpFPUacKNPNbEve_PZk',
    appId: '1:565519577576:ios:3261471db88a2d1a58345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    storageBucket: 'sayer-app-e9af3.appspot.com',
    androidClientId: '565519577576-n6g56hbkja561ltuc4168rv2j2vlqonv.apps.googleusercontent.com',
    iosClientId: '565519577576-dskq363lvgb90oeaclk49rgh94jr1a24.apps.googleusercontent.com',
    iosBundleId: 'com.example.sayeerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWvRIUWLluw6vAIpFPUacKNPNbEve_PZk',
    appId: '1:565519577576:ios:3261471db88a2d1a58345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    storageBucket: 'sayer-app-e9af3.appspot.com',
    androidClientId: '565519577576-n6g56hbkja561ltuc4168rv2j2vlqonv.apps.googleusercontent.com',
    iosClientId: '565519577576-dskq363lvgb90oeaclk49rgh94jr1a24.apps.googleusercontent.com',
    iosBundleId: 'com.example.sayeerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKxzPtGQDArggGosRF-oxjxIZ49yX0DuE',
    appId: '1:565519577576:web:6d9721c5c985f0c558345d',
    messagingSenderId: '565519577576',
    projectId: 'sayer-app-e9af3',
    authDomain: 'sayer-app-e9af3.firebaseapp.com',
    storageBucket: 'sayer-app-e9af3.appspot.com',
    measurementId: 'G-CRNL1PM2EX',
  );
}